**DSTT Assignment No: 2**

Submitted by : Apoorvamegh Anil Chechar

Roll no      : 24-27-04

Course       : MTech DATA SCIENCE 24-26

In [59]:
import numpy as np
import pandas as pd
import matplotlib as plt
import numpy.random as npr

In [29]:
'''Q1 a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape  Hint : arange'''

var1 = np.arange(0,31) # 0 and 30 Inclusive
print(var1,var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] (31,)


In [30]:
'''Q1 b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. Hint: Use the reshape function'''

var1 = np.arange(0, 31)
print(var1.shape)
var1 = np.append(var1, 0)
var2 = var1.reshape(4, 8)
print(var2)
print(var2.shape)

(31,)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30  0]]
(4, 8)


In [33]:
'''Q1. c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape.'''

var3 = var1.reshape((2,4,4))
print(var3,var3.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [-1  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30  0]]] (2, 4, 4)


In [38]:
'''Q1. d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change?
Explain what’s going on. (Hint: does reshape return a view or a copy?)'''
var2[1][0] = -1
print(var1)
print(" ")
print(var3)

[ 0  1  2  3  4  5  6  7 -1  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30  0]
 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [-1  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30  0]]]


The var1 and var3 have also changed because when we reshape var1 we are only getting a different view of the same array var1, to create seperately arrays var 2 and var3 during reshape we need to create it as copy

In [54]:
'''Q1. e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the
NumPy sum function works (and the axis argument in particular) and do the following:
1. Sum var3 over its second dimension and print the result.
2. Sum var3 over its third dimension and print the result.
3. Sum var3 over both its first and third dimensions and print the result.'''
np.sum(var3,axis=1) # Note to self: Dimension are in sequence k=0,j=1,i=2

array([[15, 28, 32, 36],
       [88, 92, 96, 69]])

In [55]:
np.sum(var3,axis=2)

array([[  6,  22,  29,  54],
       [ 70,  86, 102,  87]])

In [56]:
np.sum(var3,axis = (0,2))

array([ 76, 108, 131, 141])

In [58]:
'''Q1. f) Write code to do the following:
1. Slice out the second row of var2 and print it.
2. Slice out the last column of var2 using the -1 notation and print it.
3. Slice out the top right 2 × 2 submatrix of var2 and print it.
'''
print(var2[1,:])
print(var2[-1,:])
print(var2[:2,-2:])

[-1  9 10 11 12 13 14 15]
[24 25 26 27 28 29 30  0]
[[ 6  7]
 [14 15]]


In [62]:
'''Q2. a) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a
scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding
1 to the result of the arange function.
'''
vector = np.arange(1,11)
vector = vector+1
print(vector)

[ 2  3  4  5  6  7  8  9 10 11]


In [72]:
'''Q2. b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.
'''
matA = vector + vector.reshape(10, 1)
print(matA)

[[ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]
 [12 13 14 15 16 17 18 19 20 21]
 [13 14 15 16 17 18 19 20 21 22]]


In [74]:
'''Q2.
c) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

d) You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normaldistribution.
'''
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
print(data)


[[ 2.30057403  2.82584376  4.27343294  2.31842516  1.53619697]
 [ 0.15265465  0.38037747  3.1552367   3.15985365  0.3053915 ]
 [ 1.32139916  0.754885    0.81665769  0.70351799  4.9333233 ]
 [ 0.40725589  0.48069736 10.61191072  1.31462515  1.34458329]
 [ 0.40677435  1.38917411  2.50735162  0.28576877  3.21275598]
 [ 7.20484107  3.76792761  0.13945852  0.31259622  4.8346214 ]
 [ 0.74628315  0.24801468  0.46817373  0.73776576  0.95483591]
 [ 1.61537634  0.25532205  0.44081106  0.39111944  0.40947148]
 [ 0.58255627  0.16509397  1.54997103  2.4395153   2.11486571]
 [ 0.4172813   0.2590289   0.12800552  0.68384669  0.72407638]
 [ 1.91214606 20.56142887 15.87326059  0.35700597  1.79573993]
 [ 0.41944802  0.77478406  0.50403076  1.39978654  1.43653111]
 [ 2.23493824  0.26278747  0.68230502  7.61008831  0.64483955]
 [ 0.52633391  3.09295384  2.65941928  0.58636944  1.90519424]
 [12.69818206  0.48141077  3.14888749  5.07050767  4.96281846]
 [ 1.63869626  0.30338411  1.53275462  0.23700051  0.97

In [78]:
'''Q2. e) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print both of them.
'''
mean = np.mean(data, axis=0) #For my understanding axis are accessed in order here j=column and then i=row
std = np.std(data, axis=0)
print("Mean of each column:")
print(mean)
print("Standard deviation of each column:")
print(std)


Mean of each column:
[1.96080133 2.15464597 2.37333452 1.59531898 1.59018267]
Standard deviation of each column:
[2.34538192 3.17596572 3.14602062 1.78255345 1.68035691]


In [81]:
'''Q2. f) Now standardize the data matrix by 1) subtracting the mean off of each column,and 2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.
'''
normalized = ((data - mean) / std)
normean = np.mean(normalized, axis=0)
norstd = np.std(normalized, axis=0)
print("Normalized data mean:")
print(normean)
print("Normalized data standard deviation:")
print(norstd)

Normalized data mean:
[-1.33226763e-16  1.26010313e-16 -1.44328993e-16 -2.50910404e-16
 -9.76996262e-17]
Normalized data standard deviation:
[1. 1. 1. 1. 1.]


In [83]:
''' Q3a) A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector
[x_1, x_2, ..., x_N]^T, then the associated (square) Vandermonde matrix would be Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, ..., N]^T for any N. Do it without using a loop. Here's a stub to get you started:
def vandermonde(N):
    vec = np.arange(N) + 1
    # write your code here.
Use your function for N = 12, store it in variable named vander, and print the result.
'''
import numpy.linalg as la
def vandermonde(n):
    vec = np.arange(n) + 1
    return vec.reshape(n,1)**np.arange(n)

N = 12
vander = vandermonde(N)
print("Vandermonde matrix:")
print(vander)

Vandermonde matrix:
[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [

In [86]:
''' Q3 b) Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.Print the vector b.
'''
x = np.ones(12)
print(x)
b = np.matmul(vander, x)
print("Resultant Vector b is:")
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Resultant Vector b is:
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


In [87]:
'''Q3. c) First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.
'''
inv_vander = la.inv(vander)
naive = np.matmul(inv_vander, b)
print("Solution using matrix inversion:")
print(naive)

Solution using matrix inversion:
[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


Expected result of all the elements according to linear algebra should have been close to one which is X original, but some of the values are way distinct from the expected aray of One's.

In [89]:
''' Q3. d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?
'''
solve = la.solve(vander, b)
print("Solution using solve is:")
print(solve)

Solution using solve is:
[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


This result contains array of value close to 1 that is it is clsoe to the original data of X of one's. Which indicates it has solved as we have expected it to do.